# This is just CSS color codes and Hex format :
# https://www.w3schools.com/cssref/css_colors.asp
set  $AliceBlue             #F0F8FF
set  $AliceBlue             #F0F8FF
set  $AntiqueWhite          #FAEBD7
set  $Aqua                  #00FFFF
set  $Aquamarine            #7FFFD4
set  $Azure                 #F0FFFF
set  $Beige                 #F5F5DC
set  $Bisque                #FFE4C4
set  $Black                 #000000
set  $BlanchedAlmond        #FFEBCD
set  $Blue                  #0000FF
set  $BlueViolet            #8A2BE2
set  $Brown                 #A52A2A
set  $BurlyWood             #DEB887
set  $CadetBlue             #5F9EA0
set  $Chartreuse            #7FFF00
set  $Chocolate             #D2691E
set  $Coral                 #FF7F50
set  $CornflowerBlue        #6495ED
set  $Cornsilk              #FFF8DC
set  $Crimson               #DC143C
set  $Cyan                  #00FFFF
set  $DarkBlue              #00008B
set  $DarkCyan              #008B8B
set  $DarkGoldenRod         #B8860B
set  $DarkGray              #A9A9A9
set  $DarkGrey              #A9A9A9
set  $DarkGreen             #006400
set  $DarkKhaki             #BDB76B
set  $DarkMagenta           #8B008B
set  $DarkOliveGreen        #556B2F
set  $DarkOrange            #FF8C00
set  $DarkOrchid            #9932CC
set  $DarkRed               #8B0000
set  $DarkSalmon            #E9967A
set  $DarkSeaGreen          #8FBC8F
set  $DarkSlateBlue         #483D8B
set  $DarkSlateGray         #2F4F4F
set  $DarkSlateGrey         #2F4F4F
set  $DarkTurquoise         #00CED1
set  $DarkViolet            #9400D3
set  $DeepPink              #FF1493
set  $DeepSkyBlue           #00BFFF
set  $DimGray               #696969
set  $DimGrey               #696969
set  $DodgerBlue            #1E90FF
set  $FireBrick             #B22222
set  $FloralWhite           #FFFAF0
set  $ForestGreen           #228B22
set  $Fuchsia               #FF00FF
set  $Gainsboro             #DCDCDC
set  $GhostWhite            #F8F8FF
set  $Gold                  #FFD700
set  $GoldenRod             #DAA520
set  $Gray                  #808080
set  $Grey                  #808080
set  $Green                 #008000
set  $GreenYellow           #ADFF2F
set  $HoneyDew              #F0FFF0
set  $HotPink               #FF69B4
set  $IndianRed             #CD5C5C
set  $Indigo                #4B0082
set  $Ivory                 #FFFFF0
set  $Khaki                 #F0E68C
set  $Lavender              #E6E6FA
set  $LavenderBlush         #FFF0F5
set  $LawnGreen             #7CFC00
set  $LemonChiffon          #FFFACD
set  $LightBlue             #ADD8E6
set  $LightCoral            #F08080
set  $LightCyan             #E0FFFF
set  $LightGoldenRodYellow  #FAFAD2
set  $LightGray             #D3D3D3
set  $LightGrey             #D3D3D3
set  $LightGreen            #90EE90
set  $LightPink             #FFB6C1
set  $LightSalmon           #FFA07A
set  $LightSeaGreen         #20B2AA
set  $LightSkyBlue          #87CEFA
set  $LightSlateGray        #778899
set  $LightSlateGrey        #778899
set  $LightSteelBlue        #B0C4DE
set  $LightYellow           #FFFFE0
set  $Lime                  #00FF00
set  $LimeGreen             #32CD32
set  $Linen                 #FAF0E6
set  $Magenta               #FF00FF
set  $Maroon                #800000
set  $MediumAquaMarine      #66CDAA
set  $MediumBlue            #0000CD
set  $MediumOrchid          #BA55D3
set  $MediumPurple          #9370DB
set  $MediumSeaGreen        #3CB371
set  $MediumSlateBlue       #7B68EE
set  $MediumSpringGreen     #00FA9A
set  $MediumTurquoise       #48D1CC
set  $MediumVioletRed       #C71585
set  $MidnightBlue          #191970
set  $MintCream             #F5FFFA
set  $MistyRose             #FFE4E1
set  $Moccasin              #FFE4B5
set  $NavajoWhite           #FFDEAD
set  $Navy                  #000080
set  $OldLace               #FDF5E6
set  $Olive                 #808000
set  $OliveDrab             #6B8E23
set  $Orange                #FFA500
set  $OrangeRed             #FF4500
set  $Orchid                #DA70D6
set  $PaleGoldenRod         #EEE8AA
set  $PaleGreen             #98FB98
set  $PaleTurquoise         #AFEEEE
set  $PaleVioletRed         #DB7093
set  $PapayaWhip            #FFEFD5
set  $PeachPuff             #FFDAB9
set  $Peru                  #CD853F
set  $Pink                  #FFC0CB
set  $Plum                  #DDA0DD
set  $PowderBlue            #B0E0E6
set  $Purple                #800080
set  $RebeccaPurple         #663399
set  $Red                   #FF0000
set  $RosyBrown             #BC8F8F
set  $RoyalBlue             #4169E1
set  $SaddleBrown           #8B4513
set  $Salmon                #FA8072
set  $SandyBrown            #F4A460
set  $SeaGreen              #2E8B57
set  $SeaShell              #FFF5EE
set  $Sienna                #A0522D
set  $Silver                #C0C0C0
set  $SkyBlue               #87CEEB
set  $SlateBlue             #6A5ACD
set  $SlateGray             #708090
set  $SlateGrey             #708090
set  $Snow                  #FFFAFA
set  $SpringGreen           #00FF7F
set  $SteelBlue             #4682B4
set  $Tan                   #D2B48C
set  $Teal                  #008080
set  $Thistle               #D8BFD8
set  $Tomato                #FF6347
set  $Turquoise             #40E0D0
set  $Violet                #EE82EE
set  $Wheat                 #F5DEB3
set  $White                 #FFFFFF
set  $WhiteSmoke            #F5F5F5
set  $Yellow                #FFFF00
set  $YellowGreen           #9ACD32

